from .clas import *
from .dairy_of_class import *
from .excel import *
from .parent import *
from .pupil import *
from .subject import *
from .subject_teacher import *
from .teacher import *
from .user import *
