from .clas import *
from .dairy import *
from .excel_generation import *
from .parent import *
from .pdf_generation import *
from .pupil import *
from .subject import *
from .subject_teacher import *
from .teacher import *
from .user import *
from .word_to_pdf import *
