# Generated by Django 4.2.7 on 2023-12-19 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jounal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairyofclass',
            name='pupil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dairy_pupil', to='jounal.pupil'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('number', 'type')},
        ),
    ]
